### ISSUE TITLE
could this change color scheme together?

### ISSUE THREAD

**Issue by easyfrog** [benweier/Themr#16]
could this change color scheme together? 
like this: 
```javascript
"themr_favorites":
	[
              {
		theme: "ayu-light2.sublime-theme",
                color: "Packages/ayu/ayu-light.tmTheme"
              }
	]
```

**Comment by benweier** [comment]
Hi @easyfrog I consider this feature is out of scope for Themr. However, you can use my other package [Schemr](https://github.com/benweier/Schemr) to manage your colour schemes in the same way as Themr. To achieve changing theme and colour schemes (or any number of settings) in one command I might suggest my other other package [Preset Command](https://github.com/benweier/PresetCommand)

**Comment by easyfrog** [comment]
Yeah~ I tried [Preset Command](https://github.com/benweier/PresetCommand)!  And It's what I want. Thank you!~

**Comment by benweier** [comment]
Great to hear!
