### ISSUE TITLE
After Remove "BOXY Theme"，run themr list,also can see boxy

### ISSUE THREAD

**Issue by erwim** [benweier/Themr#17]
Hi，benweier。
I install Boxy Theme by ihodev,when i remove it.i used themr.also can find it in list theme.How can i  remove boxy theme in the list?

**Comment by benweier** [comment]
Hi @erwim did you restart Sublime after removing Boxy theme?

**Comment by erwim** [comment]
yes,restart sublime. ctrl alt p,themr,list themes,boxy theme also can find it.

**Comment by erwim** [comment]
e......i choose another pc,.i install boxy again.and i  can't find this bug......shall i take some files to you?

**Comment by benweier** [comment]
Yes that would be great. Could you copy and paste your themr favorites file here?

**Comment by erwim** [comment]
@benweier  e.....how can i copy and paste your themr favorites file?i just only can use.i'm not a developer.

{
	"bootstrapped": true,
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"A File Icon",
		"Alignment",
		"BracketHighlighter",
		"ChineseLocalizations",
		"ConvertChineseCharacters",
		"ConvertToUTF8",
		"GBK Support",
		"IMESupport",
		"Indent XML",
		"Markdown Extended",
		"Markdown Preview",
		"Monokai Extended",
		"Package Control",
		"Package Syncing",
		"Seti_UI",
		"SideBarEnhancements",
		"sublimelint",
		"Themr",
		"XssEncode"
	]
}

**Comment by benweier** [comment]
Thanks @erwim, this is only your list of installed packages.

I've looked into what Boxy does when you install and remove it. Inside your Packages folder (Preferences > Browse Packages) there will be a folder called `zzz A File Icon zzz`. Boxy asks to add this package for better file icons in the sidebar but it also creates a patched copy of your installed themes in a sub folder. These artifacts are what you're seeing in the Themr list.

Open your command palette and remove the `A File Icon` package it will remove these versions of your themes as well.
